server:
  host: localhost
  port: 80
server2:
  host: 172.168.23.4
  port: 123
client:
  url: http://${server.host}:${server.port}
  server_port: ${server2.port}
  description: client of ${.url}

selected_plan: B
plans:
  A: Plan A
  B: Plan B
plan: ${plans[${selected_plan}]}