my_class:
  _target_: 03hydra_instantiate.MyClass
  name: World!

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0
  amsgrad: false
